services:
  docelar_api:
    build: .
    container_name: docelar_api
    ports:
      - 7001:7001
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 125M
      networks:
        - database_postgres-network

volumes:
  - dado:/var/lib/postgresql/data

networks:
  database_postgres-network:
    driver: bridge
