services:
  docelar_api:
    build: .
    container_name: docelar_api
    environment:
      - NODE_ENV=production
    ports:
      - 7001:7001
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 125M
    networks:
      - docelar_api_net

networks:
  docelar_api_net:
    driver: bridge