services:
  docelar_db:
    image: postgres:16.3
    container_name: docelar_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 125M
    ports:
      - 7000:5432
    volumes:
      - docelar-api-net:/var/lib/postgresql/data
    networks:
      - docelar-api-net
volumes:
  docelar-api-net:

networks:
  docelar-api-net:
    external: true
      